export const LOGIN_ROUTE = '/login'
export const ADMIN_ROUTE = '/admin'
export const SALESMAN_ROUTE = '/salesman'
export const STOREKEEPER_ROUTE = '/storekeeper'
export const SHOP_ROUTE = '/shop'
export const STOCK_ROUTE = '/stock'